### PR TITLE
add of two options "broadcastclient" and "disable auth"

### PR DESCRIPTION
**Pull request by mpuel**
Hi,

this patch enables two configuration options in ntp.conf : the broadcast mode (the simple way) and the disabling of authentication.

Would you mind envisaging to merge those changes ?

### CODE REVIEW

**Comment by igalic** [comment]
@mpuel this will need spec tests
***
i highly recommend looking into the [github flow](https://guides.github.com/introduction/flow/index.html) work-flow for pull requests.
it recommends a separate branch for each new feature/bug (pull request)

i also recommend setting the email address you used in that commit in your github settings as an alias, so github will be able to associate this commit with your account.

**Comment by mpuel** [comment]
I have to admit that I am rather new to github and git flows :) Do you mean that I should create a branch in the puppetlabs repo rather than forking in my own repository ?

**Comment by mpuel** [comment]
I think I get your point, let's redo this.

**Comment by igalic** [comment]
\o/

no worries. git (and github) takes a while to getting used to!

**Pull request closed without merging**
