### PR TITLE
Loc+ strings edit

### PR DESCRIPTION
**Pull request by jbondpdx**
General edit of the ntp module readme, in prep for localization work and adding docs strings to code.

Of note, I've (mostly) pulled out "valid values" from descriptions, but added data types at the front of the descriptions. These types appeared to cover valid values for the most part, and having them at the front of the description will make strings import easier and let the user know up front what they are dealing with.

### CODE REVIEW

**Comment by jbondpdx** [comment]
Oh, I forgot I did a progress commit... I can squash these if you want.

**Comment by HAIL9000** [comment]
@jbondpdx If this is ready for review I'd say go ahead and squash that WIP commit! But if you have more work to do I'd wait and squash later

**Comment by jbondpdx** [comment]
Nah, @HAIL9000 , no more work on it... I don't PR until it's ready for review. And I've squashed the commits (someday I won't have to look it up every time!).

**Comment by tphoney** [comment]
@jbondpdx looks good to me, nice changes 👍

**Pull request merged**
