### PR TITLE
Avoid collision between OS and OS family name

### PR DESCRIPTION
**Pull request by jonhattan**
The hiera hierarchy implies a collision when OS name and family are the same (Ex: Debian family). Here's a proposal for fix.

### CODE REVIEW

**Comment by pmcmaw** [comment]
Closing and reopening to resolve Travis/bundler issues, this is caused due to https://tickets.puppetlabs.com/browse/MODULES-6339.

**Comment by pmcmaw** [comment]
Hey @jonhattan if you were able to resolve this conflict I will get this change merged for you.

**Comment by jonhattan** [comment]
@pmcmaw done!

**Comment by pmcmaw** [comment]
@jonhattan Fantastic! 
Currently working on a release so you should see them changes soon! 👍

**Pull request merged**
