### PR TITLE
(MODULES-3397) fix default Solaris settings

### PR DESCRIPTION
**Pull request by vchepkov**
Module creates NTP v4 compatible configuration.
Correct names for NTP v4 packages and service

### CODE REVIEW

**Comment by ferventcoder** [comment]
@vchepkov Howdy! I looked over this PR and it seems pretty straightforward. I'll need to bring in @DavidS to verify this is correct. 

Can I ask you to do a couple of things for me in the interim? I know this change looks possibly trivial, but we'd like to get a JIRA ticket assigned on it so we have something to point to for release notes (and for tracking purposes). If you could file a ticket at https://tickets.puppet.com/browse/MODULES (create button in top row). Select ntp as part of the components and fill in as many details as you can. Then let us know what ticket that is.

The second thing we'll need you to do is prepend the git commit message with the ticket number that you get back, something like MODULES-12345 - so your commit would look like `(MODULES-1234) Fix default Solaris settings`.

Thanks and apologies on not getting to this sooner!

cc @DavidS for correctness.

**Comment by vchepkov** [comment]
I actually have created ticket sometime ago
https://tickets.puppetlabs.com/browse/MODULES-3397

**Comment by ferventcoder** [comment]
@vchepkov Fantastic. Do you need any help associating the commit with the ticket?

**Comment by vchepkov** [comment]
I amended commit message to include ticket number. thanks for the help

**Comment by ferventcoder** [comment]
@vchepkov not to nitpick too much, but we are hoping for exactly as I prescribed. "(MODULES-3397) Fix default Solaris settings" - the important bits being that the JIRA ticket is surrounded by parentheses and there is no other separator between that and the commit message. If you want a more in depth review of contributing guidelines and our hope for the commit body as well, please review https://github.com/puppetlabs/puppetlabs-ntp/blob/master/CONTRIBUTING.md.

HTH

**Comment by vchepkov** [comment]
My bad, fixed

**Comment by DavidS** [comment]
@vchepkov thank you very much for your contribution!

**Pull request merged**
